Repository ECO-ufpel/backend, pull requests merged in 2024-03, with the labels that each got.

#19 Create future consumption data getter service
  src/main/java/com/ecoufpel/ecoufpelapp/domains/sensor/DataConsumptionDTO.java
  src/main/java/com/ecoufpel/ecoufpelapp/domains/sensor/DataConsumptionID.java
  src/main/java/com/ecoufpel/ecoufpelapp/domains/ufpel_data/TimeIntervals.java
  src/main/java/com/ecoufpel/ecoufpelapp/repositories/DataConsumptionRepository.java
  src/main/java/com/ecoufpel/ecoufpelapp/services/GetConsumptionDataService.java
  src/main/java/com/ecoufpel/ecoufpelapp/services/InsertDataConsuptionService.java
  src/main/java/com/ecoufpel/ecoufpelapp/services/initializer/GetConsumptionDataInitializer.java
  src/main/java/com/ecoufpel/ecoufpelapp/websocket/WebSocketEventListener.java
  src/main/resources/database/migration/V4_0__create_classroom_data_aggregation_table.sql
  src/main/resources/database/migration/v4_1__alter_table_time_intervals_change_time_type.sql
Labels: enhancement

#23 fix: naming of migration to flyway format
  src/main/resources/database/migration/V1_1__create_user_table.sql
  src/main/resources/database/migration/V4_1__alter_table_time_intervals_change_time_type.sql
Labels: bug

#29 Feat/update activity
  src/main/java/com/ecoufpel/ecoufpelapp/domains/ufpel_data/CourseChangeDTO.java
  src/main/java/com/ecoufpel/ecoufpelapp/repositories/CoursesRepository.java
  src/main/java/com/ecoufpel/ecoufpelapp/services/GetActivityChangeService.java
  src/main/java/com/ecoufpel/ecoufpelapp/websocket/WebSocketHandler.java
Labels: enhancement, WebSocket

#31 Feat/randomize bd data pool
  src/main/java/com/ecoufpel/ecoufpelapp/domains/ufpel_data/ExpectedConsumptionMessageDTO.java
  src/main/java/com/ecoufpel/ecoufpelapp/repositories/DataConsumptionRepository.java
  src/main/java/com/ecoufpel/ecoufpelapp/services/GetConsumptionDataService.java
  src/main/java/com/ecoufpel/ecoufpelapp/services/GetExpectedConsumptionService.java
  src/main/java/com/ecoufpel/ecoufpelapp/websocket/WebSocketHandler.java
Labels: enhancement

#32 fix: control of websocket sessions listening on activity change
  src/main/java/com/ecoufpel/ecoufpelapp/services/GetActivityChangeService.java
  src/main/java/com/ecoufpel/ecoufpelapp/websocket/WebSocketHandler.java
Labels: bug, WebSocket

#34 Hotfix/history data
  src/main/java/com/ecoufpel/ecoufpelapp/domains/sensor/ClassroomDataAggregation.java
  src/main/java/com/ecoufpel/ecoufpelapp/domains/websocket/CourseChangeDTO.java
  src/main/java/com/ecoufpel/ecoufpelapp/domains/websocket/ExpectedConsumptionMessageDTO.java
  src/main/java/com/ecoufpel/ecoufpelapp/repositories/CoursesRepository.java
  src/main/java/com/ecoufpel/ecoufpelapp/repositories/DataConsumptionRepository.java
  src/main/java/com/ecoufpel/ecoufpelapp/services/GetActivityChangeService.java
  src/main/java/com/ecoufpel/ecoufpelapp/services/GetExpectedConsumptionService.java
Labels: bug
